# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proyecto_QT/Menu_Ajustes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TowerDefenseMenuAjustes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondoajustes = QtWidgets.QLabel(self.centralwidget)
        self.fondoajustes.setGeometry(QtCore.QRect(0, 0, 581, 481))
        self.fondoajustes.setStyleSheet("background-image: url(:/images/second_background.jpg);")
        self.fondoajustes.setText("")
        self.fondoajustes.setObjectName("fondoajustes")
        self.tituloajustes = QtWidgets.QLabel(self.centralwidget)
        self.tituloajustes.setGeometry(QtCore.QRect(210, 50, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(28)
        self.tituloajustes.setFont(font)
        self.tituloajustes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tituloajustes.setLineWidth(1)
        self.tituloajustes.setTextFormat(QtCore.Qt.PlainText)
        self.tituloajustes.setObjectName("tituloajustes")
        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(120, 150, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.label_vol = QtWidgets.QLabel(self.centralwidget)
        self.label_vol.setGeometry(QtCore.QRect(100, 200, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_vol.setFont(font)
        self.label_vol.setObjectName("label_vol")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(500, 410, 41, 41))
        self.backButton.setStyleSheet("image: url(:/images/go_back.png);")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.label_vol_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_vol_2.setGeometry(QtCore.QRect(120, 250, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_vol_2.setFont(font)
        self.label_vol_2.setObjectName("label_vol_2")
        self.volumenSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.volumenSlider_2.setGeometry(QtCore.QRect(250, 250, 129, 22))
        self.volumenSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.volumenSlider_2.setObjectName("volumenSlider_2")
        self.label_vol_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_vol_3.setGeometry(QtCore.QRect(170, 300, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_vol_3.setFont(font)
        self.label_vol_3.setObjectName("label_vol_3")
        self.idline_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.idline_2.setGeometry(QtCore.QRect(250, 300, 119, 20))
        self.idline_2.setObjectName("idline_2")
        self.volumenSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumenSlider.setGeometry(QtCore.QRect(250, 200, 129, 22))
        self.volumenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumenSlider.setObjectName("volumenSlider")
        self.idline = QtWidgets.QLineEdit(self.centralwidget)
        self.idline.setGeometry(QtCore.QRect(250, 150, 119, 20))
        self.idline.setObjectName("idline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 20))
        self.menubar.setObjectName("menubar")
        self.menuTOWER_DEFENSE_GAME = QtWidgets.QMenu(self.menubar)
        self.menuTOWER_DEFENSE_GAME.setObjectName("menuTOWER_DEFENSE_GAME")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTOWER_DEFENSE_GAME.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tituloajustes.setText(_translate("MainWindow", "AJUSTES"))
        self.label_ID.setText(_translate("MainWindow", "ID de usuario"))
        self.label_vol.setText(_translate("MainWindow", "Volumen Música"))
        self.label_vol_2.setText(_translate("MainWindow", "Volumen SFX"))
        self.label_vol_3.setText(_translate("MainWindow", "Idioma"))
        self.idline_2.setText(_translate("MainWindow", "Español"))
        self.menuTOWER_DEFENSE_GAME.setTitle(_translate("MainWindow", " "))
import Resource_File_General_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TowerDefenseMenuAjustes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
